baseURL = "https://burnett.wtf"
title   = "UnDeR mAj0r CoNsTrUcT1On"

DefaultContentLanguage = "en"

#theme = "hugo-theme-hello-friend-ng" # original theme
theme = "hugo-theme-hello-friend-ng_jlb-edits" # JLB edits

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "CC0"

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  Thoughts = "/thoughts/:year/:month/:title/"

[author]
  name = "J. Burnett"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = ""
  keywords = "research, ecologist, data science, usgs, birds, ornithology, avian"
  images = [""]

  homeSubtitle = "Research Ecologist & Mendenhall Postdoctoral Fellow"
 # homeSubtitle2 = "Science Analytics & Synthesis"
  homeSubtitle3 = "U.S. Geological Survey"
  # Set disableReadOtherPosts to `true` in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
#    logoText     = "$ cd /home/"
    logoText     = "$ Rscript "
    logoHomeLink = "/"
    logoColor    = "#7FFF00"# Set to a valid CSS color to change the cursor in the logo.
  
  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/trashbirdecology"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/trashbirdecol"
  [[params.social]]
    name = "email"
    url  = "mailto:jessicaleighburnett@gmail.com"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4137899/jessica-burnett"
#  [[params.social]]
#    name = "linkedin"
#    url  = "https://www.linkedin.com/"


#[languages]
#  [languages.en]
#    subtitle  = "Hello Friend NG Theme"
#    weight    = 1
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" #target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "thoughts"
    name       = "Thoughts"
    url        = "thoughts/"
  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "research/"
  [[menu.main]]
    identifier = "code"
    name       = "Code"
    url        = "code/"
