baseurl = "http://burnett.wtf"
languageCode = "en-us"
theme = "hugo-theme-hello-friend_jlb"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Jessica Burnett, Ph.D."
    subtitle = "Research Ecologist, U.S. Geological Survey"
    keywords = "ecology reproducibility"
    copyright = ""
    menuMore = "May I have some more, please?"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"


    [languages.en.params.logo]
      logoText = "$ cd home" # this is the fun thing in upper LHS of page
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


   [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "code"
        name = "Code"
        url = "/code"
      [[languages.en.menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research"
      [[languages.en.menu.main]]
        identifier = "presentations"
        name = "Presentations"
        url = "/presentations"
      [[languages.en.menu.main]]
        identifier = "thoughts"
        name = "Thoughts"
        url = "/thoughts"
