# Some required things
baseURL = "http://burnett.wtf"
title   = "UnDeR mAj0r CoNsTrUcT1On"
languageCode = "en-us"

# Upper left logo
 [params.logo]
    logoText     = "$ Rscript "
    logoHomeLink = "/"
    logoColor    = "#7FFF00"# neon green color
  

# Theme specs
#theme = "hugo-theme-hello-friend-ng" # original theme
theme = "hugo-theme-hello-friend-ng_jlb-edits" # JLB edits

# Footer shit
copyright = "CC0"

# Meta
[author]
  name = "J. Burnett"


# Blog/posts/thoguhts things
[permalinks]
  Thoughts = "/thoughts/:year/:month/:title/"


[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"



# Metadata mostly used in document's head
  description = ""
  keywords = "research, ecologist, data science, usgs, birds, ornithology, avian"
  images = [""]

# Home page subtitles
  homeSubtitle = "Research Ecologist & Mendenhall Postdoctoral Fellow"
 # homeSubtitle2 = "Science Analytics & Synthesis"
  homeSubtitle3 = "U.S. Geological Survey"

# Directory name of your blog content (default is `content/posts`)
  contentTypeName = "thoughts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

 # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/trashbirdecology"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/trashbirdecol"
  [[params.social]]
    name = "email"
    url  = "mailto:jessicaleighburnett@gmail.com"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4137899/jessica-burnett"
#  [[params.social]]
#    name = "linkedin"
#    url  = "https://www.linkedin.com/"




[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'